services:

  pg:
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-crypto_db_tg_webapp}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    networks:
      - inner_crypto_invest_pools_service
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_RUN_PORT:-8000}:8000"
    networks:
      - inner_crypto_invest_pools_service
    depends_on:
      - pg
    environment:
      - DEBUG=${DEBUG:-True}
      - APP_RUN_HOST=${APP_RUN_HOST:-0.0.0.0}
      - APP_RUN_PORT=${APP_RUN_PORT:-8000}

      - POSTGRES_ADDRESS=${POSTGRES_ADDRESS:-pg}
      - POSTGRES_DB=${POSTGRES_DB:-crypto_db_tg_webapp}
      - POSTGRES_ECHO=${POSTGRES_ECHO:-False}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_POOL_SIZE=${POSTGRES_POOL_SIZE:-10}
      - POSTGRES_MAX_OVERFLOW=${POSTGRES_MAX_OVERFLOW:-20}

      - SQLADMIN_SECRET_KEY=${SQLADMIN_SECRET_KEY:-secret_key_12345}
      - SQLADMIN_USERNAME=${SQLADMIN_USERNAME:-admin}
      - SQLADMIN_PASSWORD=${SQLADMIN_PASSWORD:-password}

      - DATA_UPD_INTERVAL_CURRENCY=${DATA_UPD_INTERVAL_CURRENCY:-10}
      - DATA_UPD_OFFERS_TIME_HOUR_UTC=${DATA_UPD_OFFERS_TIME_HOUR_UTC:-0}
      - DATA_UPD_OFFERS_TIME_RANDOM_MINUTE_FORM_TUPLE=${DATA_UPD_OFFERS_TIME_RANDOM_MINUTE_FORM_TUPLE:-(0, 25)}
      - SCRAPER_DEBUG=${SCRAPER_DEBUG:-False}  # With false on creation first scraping will run with debug anyway, next with log level warning

      - MEDIA_FILES_ALLOWED_EXTENSIONS=${MEDIA_FILES_ALLOWED_EXTENSIONS:-['.jpg', '.jpeg', '.png', '.gif', '.svg', '.ico', '.webp']}

      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-["*"]}

      - USER_CACHE_TTL=${USER_CACHE_TTL:-6}
      - USER_MAX_CACHED=${USER_MAX_CACHED:-1000}

    command: /app/start.sh
    volumes:
      - media_files:/app/media

networks:
  inner_crypto_invest_pools_service:
    external: false
    driver: bridge

volumes:
  pg_data:
  media_files: