"""pool upd

Revision ID: 4929299bb3ee
Revises: 765edf796665
Create Date: 2024-09-10 13:04:26.691661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4929299bb3ee'
down_revision: Union[str, None] = '765edf796665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pools', sa.Column('parsing_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pools', 'parsing_source')
    # ### end Alembic commands ###
