"""create clicker table

Revision ID: f022e615e4de
Revises: 74799d18b775
Create Date: 2024-09-29 19:42:38.262008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f022e615e4de'
down_revision: Union[str, None] = '74799d18b775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clickers',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time_spent', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('coin', sa.String(), nullable=True),
    sa.Column('app_launch_date', sa.Date(), nullable=True),
    sa.Column('token_launch_date', sa.Date(), nullable=True),
    sa.Column('telegram_channel', sa.String(), nullable=True),
    sa.Column('partners', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clickers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clickers')
    # ### end Alembic commands ###
