"""add media

Revision ID: c18422efc702
Revises: 9e76a07d6da3
Create Date: 2024-08-24 11:35:55.490782

"""
from typing import Sequence, Union

from fastapi_storages.integrations.sqlalchemy import FileType
from alembic import op
import sqlalchemy as sa

from core import chain_storage, coin_storage, pool_storage

# revision identifiers, used by Alembic.
revision: str = 'c18422efc702'
down_revision: Union[str, None] = '9e76a07d6da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chains', sa.Column('logo', FileType(storage=chain_storage), nullable=True))
    op.add_column('coins', sa.Column('logo', FileType(storage=coin_storage), nullable=True))
    op.add_column('pools', sa.Column('logo', FileType(storage=pool_storage), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pools', 'logo')
    op.drop_column('coins', 'logo')
    op.drop_column('chains', 'logo')
    # ### end Alembic commands ###
