"""offer\'s lock_period non-nullable again 

Revision ID: 0ab539bf013c
Revises: 9e81e32d0169
Create Date: 2024-09-11 16:05:43.100773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab539bf013c'
down_revision: Union[str, None] = '9e81e32d0169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coin_pool_offers', 'lock_period',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coin_pool_offers', 'lock_period',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
